[tool.poetry]
name = "gin-scoring"
version = "0.1.0"
description = ""
authors = ["Olivier Philippon <olivier@dunsap.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.5"
django-environ = "^0.9.0"
psycopg2 = "^2.9.3"
Jinja2 = "^3.1.2"
django-ninja = "^0.18.0"
gunicorn = "^20.1.0"
whitenoise = "^6.2.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
pywatchman = "^1.4.1"
ipython = "^8.4.0"

[tool.black]
line-length = 119
target-version = ['py310']

[tool.isort]
py_version = 310
profile = "black"
line_length = 119
multi_line_output = 3
known_first_party = ["apps"]
combine_as_imports = true

[tool.mypy]
python_version = "3.10"
mypy_path = "src/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
